def errorCheck(n):
    try:
        n = int(n)
    except Exception:
        return -1
    return n
